version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - mongodb:27017/shop
    networks:
      - my-network
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  mongodb_data:
