name: Deploy CICD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    services:
      mongo:
        image: mongo:4.4.6
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Clear old session docker
      run: docker-compose down -v
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
    - name: Monitoring with pm2
      run: pm2 restart run
    - name: Deploy to Docker
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
        docker-compose -f ./docker-compose.yml build
        docker-compose -f ./docker-compose push
   
