name: CICD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: DEPLOY CICD
    services:
      mongo:
        image: mongo:4.4.6
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build Artifact
      run: |
        cd ${{ github.workspace }}/frontend
        rm -rf node_modules
        npm install
        npm run build
        rm -rf node_modules
        cd ${{ github.workspace }}/backend
        rm -rf node_modules
        cd ${{ github.workspace }}
        zip -r run.zip . 
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RUN
        path: run.zip
        retention-days: 7
    - name: Verify uploaded artifact
      run: |
        echo "Artifact contents:"
        ls -la ${{ github.workspace }}/run.zip    
  deploy:
    runs-on: [self-hosted, linux]
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with: 
        name: RUN
    - name: List files before unzip
      run: ls -la 
    - name: List files in zip
      run: unzip -l run.zip
    - name: Deploy to Server
      run: |
        docker-compose down -v
        docker ps -q --filter "publish=3000" --filter "publish=80" --filter "publish=8080" --filter "publish=27017" | xargs -r docker stop
        docker ps -a -q | xargs -r docker rm
        docker-compose config
        docker ps
        docker-compose logs -f
        docker-compose up -d
    - uses: ncipollo/release-action@v2
      with:
        artifacts: "./RUN/run-v${{ github.run_number }}.zip"
        body: "Release new Build"
        tag: release-v0.0.${{ github.run_number }}
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        replacesArtifacts: false
        allowUpdates: true
        prerelease: true
