name: Deploy CICD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    name: DEPLOY CICD
    services:
      mongo:
        image: mongo:4.4.6
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Artifact
      run: |
        cd /home/duyle/run/_work/ubuntu/ubuntu
        cd frontend
        rm -rf node_modules
        npm install
        npm run build
        cd ./backend
        rm -rf node_modules
        npm install
        cd ~/ && zip -r run.zip run/ && cp run.zip ~/
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/duyle/run.zip"
        body: "Release new Build"
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        replacesArtifacts: false
        allowUpdates: true
        prerelease: true
