name: CICD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: DEPLOY CICD
    services:
      mongo:
        image: mongo:4.4.6
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build Artifact
      run: |
        cd ${{ github.workspace }}/frontend
        rm -rf node_modules
        npm install
        npm run build
        rm -rf node_modules
        cd ${{ github.workspace }}/backend
        rm -rf node_modules
        cd ${{ github.workspace }}
        zip -r run.zip . 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RUN
        path: run.zip
        retention-days: 7
    - name: Verify uploaded artifact
      run: |
        echo "Artifact contents:"
        ls -la ${{ github.workspace }}/run.zip    
  deploy:
    runs-on: [self-hosted, linux]
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with: 
        name: RUN
    - name: Deploy to Server
      run: |
        unzip run.zip
        docker-compose config
        docker ps
        docker-compose logs -f
        docker-compose up -d
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./run/run.zip"
        body: "Release new Build"
        tag: release-v0.0.${{ github.run_number }}
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        replacesArtifacts: false
        allowUpdates: true
        prerelease: true
